# docker-compose.yml
version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
